### ISSUE TITLE
Description and docker-compose snippet are missing

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/docker-event-store#1]
Description is missing. Please update README file and also include docker-compose snippet on how to use it inside BDE stack (i.e. a pilot case).

**Comment by gioargyr** [comment]
We are dealing with configuration issues with this repo since the last changes in BDE-Swarm-cluster. As soon as we have a stable version the README.md will be updated.

**Comment by gioargyr** [comment]
This repository is now substituted by docker-eventretrieve.
It will be deleted in a few hours.
